services:
  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonflydb
    hostname: dragonfly
    privileged: true
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"